development:
  adapter: postgresql
  encoding: utf8
  database: oldetownepizza_development
  pool: 5
  username: oldetownepizza
  password:

test:
  adapter: postgresql
  encoding: utf8
  database: oldetownepizza_test
  pool: 5
  username: oldetownepizza
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: oldetownepizza_production
  pool: 5
  username: oldetownepizza
  password:
